### ISSUE TITLE
add more Hackathon related activities 

### ISSUE THREAD

**Issue by starlightknown** [starlightknown/hacky#15]
**Description**

add a few more activities related to hackathons or programming in [activites](https://github.com/kcoder63/hacky/blob/main/hacky/files/activities.csv)
They should start with - `with` and don't use commas

**Comment by Salonijain1248** [comment]
Hey! I would like to work on it.

**Comment by kcoder63** [comment]
Hey yes, thank you. Find some phrases for example `with bugs` `with animations` `with hardware` etc and add it to the file mentioned in the description of this issue

**Comment by Divyaansh313** [comment]
Can I also work on this issue?

**Comment by kcoder63** [comment]
sure! go ahead

**Comment by Salonijain1248** [comment]
I cannot clone this repo. When I try to clone it, none of the contents show up.

**Comment by adityaraute** [comment]
Could be because the `csv` file has no commas. Why this antithesis?
